LANG_JSON_DATA = {
	"app_name" : "PadelScore",
	"option_start" : "Play",
	"option_finish" : "Finish game",
	"option_discard" : "Discard game",
	"option_history" : "Results",
	"option_stats" : "Statistics",
	"option_stats_static" : "Profile",
	"option_stats_bar" : "Summary",
	"option_tutorial" : "HowTo",
	"action_skip" : "Exit",
	"action_save" : "Save match",
	"action_discard" : "Discard match",
	"action_continue" : "Next tip",
	"action_finish" : "Finish match",
	"action_done" : "Done!",
	"action_more" : "Get more data",
	"str_current" : "Current match:",
	"str_game" : "GAME",
	"str_set1" : "SET1",
	"str_set2" : "SET2",
	"str_set3" : "SET3",
	"error_no_match" : "No current match found",
	"error_no_data" : "No stored matches",
	"discard_success" : "Match discarded!",
	"finish_success" : "Match saved!",
	"tutorial_step1" : "Swipe horizontally to increase or decrease points score",
	"tutorial_step2" : "Swipe vertically to increase or decrease games score",
	"tutorial_step3" : "When playing, use bezel to save or discard a match",
	"tutorial_step4" : "Check match results and review your statistics!",
	"confirm_save" : "Save\ncurrent match\nand finish?",
	"confirm_discard" : "Discard\ncurrent match?"
};


